### ISSUE TITLE
General Question

### ISSUE THREAD

**Issue by Proper231** [vicuna-tools/vicuna-installation-guide#17]
I know other Vicuna installs require you to get the llama weight in order to run vicuna, is that also the case for this installation?

**Comment by fredi-python** [comment]
No, you don't need to have the llama weights for this install. 
This guide uses the full vicuna weights, instead of only the deltas. 
Normally you need to merge the vicuna deltas with the llama weights, but thanks to a user on HF(HuggingFace) who has already merged it, we can use the full vicuna weights.

**Comment by Proper231** [comment]
ahhh ok, thank you for the clarification
